/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 brain.gltf 
Author: soufiane oujihi (https://sketchfab.com/sararoujihi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brain-3d-33dd384ebe35410eaca42f21e14f14a3
Title: Brain 3D
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brain.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/brain.gltf')
